# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='due_date',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_due',
            field=models.CharField(max_length=64),
        ),
    ]
